/*
 * Manage Contractors APIs
 * This API supports all services required to manage Employees on HR system
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ERRORUNKNOWN;
import io.swagger.client.model.Employee;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContractorsApi
 */
@Ignore
public class ContractorsApiTest {

    private final ContractorsApi api = new ContractorsApi();

    
    /**
     * Deletes an Employee record
     *
     * Deletes the profile of an employee.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contractorsEmployeeIDDeleteTest() throws ApiException {
        Integer employeeID = null;
        api.contractorsEmployeeIDDelete(employeeID);

        // TODO: test validations
    }
    
    /**
     * Retrieves an Employee record
     *
     * Retrieves the profile of an employee.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contractorsEmployeeIDGetTest() throws ApiException {
        Integer employeeID = null;
        Employee response = api.contractorsEmployeeIDGet(employeeID);

        // TODO: test validations
    }
    
    /**
     * Retrieves all Employee records
     *
     * Retrieves the profile of all employees.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contractorsGetTest() throws ApiException {
        ERRORUNKNOWN response = api.contractorsGet();

        // TODO: test validations
    }
    
    /**
     * Creates an Employees
     *
     * Registers a new employee for the client.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contractorsPostTest() throws ApiException {
        Employee employee = null;
        api.contractorsPost(employee);

        // TODO: test validations
    }
    
}
